keploy/blog-website

components/header.tsx
pages/community/[slug].tsx
pages/community/index.tsx
pages/index.tsx
pages/technology/[slug].tsx
pages/technology/index.tsx
styles/index.css

Fixes issue: [#1235](https://github.com/keploy/keploy/issues/1235)

Blog Website Header to Match Main Website

---

.env.local.example
components/layout.tsx
components/meta.tsx
pages/community/[slug].tsx
pages/community/index.tsx
pages/index.tsx
pages/technology/[slug].tsx
pages/technology/index.tsx

Fixes the [issue](https://github.com/keploy/keploy/issues/1503)

Changes in the meta tag and the layout tag and the changes that follows

---

components/topBlogs.tsx

Fixes the URLS for techBlogs and Community Blogs on the Homepage.

changing the URLS on Homepage

---

components/TableContents.tsx
components/container.tsx
components/containerSlug.tsx
components/post-body.tsx
pages/community/[slug].tsx
pages/technology/[slug].tsx

Fixes the [Issue](https://github.com/keploy/keploy/issues/1240).

Adding the Table of Contents

---

components/TagsPostPreview.tsx
components/TagsStories.tsx
components/meta.tsx
components/tags.tsx
lib/api.ts
pages/community/index.tsx
pages/tags/[slug].tsx
pages/tags/index.tsx
pages/technology/[slug].tsx

Fixes the [Issue](https://github.com/keploy/keploy/issues/1591).

Adding the tags

---

components/TagsPostPreview.tsx
components/TagsStories.tsx
components/tags.tsx
lib/api.ts
pages/tags/[slug].tsx
pages/tags/index.tsx

This PR fixes and covers the problems faced by previous tag's PR.
Changes made:-
1. Latest 95 post's tags will be fetched anymore resulted in badgateway.
2. All the related posts to those Tags will come.

Fixing tags

---

components/post-body.tsx
lib/api.ts
pages/tag/[slug].tsx
pages/tag/index.tsx

Fixes #[1669](https://github.com/keploy/keploy/issues/1669)

Toc fixed 

---

components/author-description.jsx

This PR fixes the issue - [Link](https://github.com/keploy/keploy/issues/1752)
- Inconsistent profile image in author description section

Fix: Aspect Ratio of Author Profile Image, Author Description

---

components/TableContents.tsx
components/header.tsx
components/post-preview.tsx
components/postByAuthorMapping.tsx
package-lock.json
package.json
pages/community/[slug].tsx
pages/technology/[slug].tsx

This PR fixes the issue - [Link](https://github.com/keploy/keploy/issues/1664)

Add animations to blog website

---

components/hero-post.tsx
pages/technology/index.tsx

- Correcting the routing for the blog-website's hero posts.

Correcting routing for the Hero Post.

---

package-lock.json
pages/community/[slug].tsx
pages/technology/[slug].tsx

fixes #[issue](https://github.com/keploy/keploy/issues/1838#issuecomment-2076957131)

correcting fallback

---

components/more-stories.tsx
components/post-body.module.css
lib/api.ts
pages/community/[slug].tsx
pages/community/index.tsx
pages/technology/[slug].tsx
pages/technology/index.tsx
styles/index.css

Following has been done in the pr :
1. Increased the pagination factor in both /technology /community to display all the blogs.
2. Made the table lines availabe which were disappeared.
3. Added a search bar in /technology , /community (Currently on the basis of the blog's name)
4. made H1 H2 H3 bold by default.

Solvingerrors

---

components/footer.tsx

This PR aims to solve https://github.com/keploy/keploy/issues/2103
- Corrected the CNCF link URL.
- Updated the image links to open in a new tab.

Update CNCF Landscape URL and target attribute

---

components/footer.tsx
components/header.tsx

fix: github api fetch call

---

styles/index.css

Closes https://github.com/keploy/keploy/issues/2163
Screenshot after fix

Fix overflowing video in blogs

---

.env.local.example
components/AuthorMapping.tsx
components/ReviewingAuthor.tsx
components/TagsPostPreview.tsx
components/TagsStories.tsx
components/avatar.tsx
components/hero-post.tsx
components/more-stories.tsx
components/post-body.tsx
components/post-preview.tsx
components/postByAuthorMapping.tsx
components/topBlogs.tsx
lib/api.ts
lib/constants.ts
next.config.js
pages/authors/[slug].tsx
pages/authors/index.tsx
pages/community/[slug].tsx
pages/community/index.tsx
pages/technology/[slug].tsx
pages/technology/index.tsx
types/post.ts

Closes https://github.com/keploy/keploy/issues/2320

fix: blog URL handler and Update endpoints

---

components/author-description.jsx
components/post-body.tsx
pages/community/[slug].tsx

refactors the author-description.js

chore: refactoring author-description

---

lib/api.ts

* hot fix for ensuring latest blog is shown on community page
* solves https://github.com/keploy/keploy/issues/2392

chore: hot fix

---

lib/api.ts
pages/community/[slug].tsx
pages/technology/[slug].tsx

Issue - https://github.com/keploy/keploy/issues/2435
In community/slug or technology/slug I have
1. Added tag filter
2. Removed same post from "more posts" section
3. limited more posts to 6-7 posts.

feat: add tag based suggestions

---

components/author-description.jsx
pages/authors/index.tsx

fix: linkedin metadata updated

---

lib/api.ts
pages/authors/[slug].tsx

the current implementation calls all posts by all authors and then filters on the website, optimized queries for specific user implementation
Part of https://github.com/keploy/keploy/issues/2464

chore: optimize queries for specific user

---

components/hero-post.tsx

- Improve the outline of the hero post on hovering 
- Remove table of content string from the description of the post.

refactor: improve UI design for hero post

---

components/PostHeaderAuthors.tsx
components/TableContents.tsx
components/TagsPostPreview.tsx
components/author-description.jsx
components/header.tsx
components/latest-post.tsx
components/post-body.tsx
components/post-preview.tsx
components/testimonials.tsx
components/topBlogs.tsx
components/tweets.tsx
components/waitlistBanner.jsx
lib/api.ts
pages/community/[slug].tsx
pages/community/index.tsx
pages/index.tsx
pages/technology/[slug].tsx
utils/sanitizeStringForUrl.ts

1. Update the Twitter Logo
2. Copy Blog URL Functionality with Copy Link Logo 
3. Copy A Section From the Blog URL functionality 
4. Sanitize URL functionality
5. Handle nil description and linkedin by removing those items and handle type parsing
6. Update the Join WaitList banner to Sign In with redirection to `app.keploy.io`
7. Refactor hero section on home page by integrating Latest Post section on the hero's left section
8. Redesign Queries on Hero Page to fetch most viewed blogs for each section and enhance read more section design
9. Create New GetAllPosts Query to fetch all posts for latest post rendering
10. Fix Nil Description on Post-Author

refactor: blog website 

---

components/header.tsx

Fixes: #[issue-number]
- Fixed the signin button that was redirecting to a blank/broken screen
- Changed the broken url
- Fixed the signin URL
- Tested it on local, the link redirects to the signin page
- Tried to run npm run build, build was successful
-
- **New Dependencies:** 
- **Configuration Changes:**

fix: signin error fix on header

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/build.yml

This PR adds
- NEXT_PUBLIC_WORDPRESS_API_URL to support client side pagination
- add github PR template

chore: update build config

---

pages/_document.tsx

I have added google adsense meta data field inside the pages/documents.tsx

Added google-adsense to the blog website 

---

components/Adbanner.tsx
components/cover-image.tsx
components/more-stories.tsx
components/post-body.tsx
components/testimonials.tsx
package-lock.json
package.json
pages/_document.tsx
pages/technology/[slug].tsx
public/ads.txt

Added Google adsense component

chore: Added google adsense component

---

.github/scripts/lighthouse-report.js
.github/workflows/lighthouse.yml
pages/_document.tsx

Lighthouse Action has been added to the blog website. 
- Added  lighthouse-integration in the repo

feat: Added Updated lighthouse integration

---

components/Adbanner.tsx
components/cover-image.tsx
components/post-body.tsx
pages/_document.tsx
public/ads.txt

I have modified and updated the google adsense component
[
](url)

fix:  Modifed the Google adsense component

---

components/Adsolt.tsx
components/layout.tsx
components/tag.tsx

Fixed the  "multiple property codes with AdSense tag"

fix: google adsense multiple tag issue fix

---

components/layout.tsx
pages/_document.tsx

I have added the publisher script and also removed the redundant AdSense script from the _document.tsx.

fix: add publisher script

---

components/post-body.tsx

- This PR fixes the behaviour in which on clicking any heading, the url gets copied to the clipboard and is shown to the user on the browser url.
- Fixed: On clicking any heading, the user is getting scrolled past it. The navbar is hiding the text.
- When the user scrolls and the headings change, the url is also updated automatically according to that.
- Changes in `components/post-body.tsx`, for pushing the new url to the browser tab.
- Added `useEffect` hook so that, on scrolling, the url gets changed in the browser's tab.
- Added `useEffect` hook, so that, whenever user enters a url with any heading - `#`, the user will be redirected to it eaisly.
-
-
-
https://github.com/user-attachments/assets/b840e1e9-87d0-4a0c-9a3b-460c45c9fc2c
- **New Dependencies:** 
- **Configuration Changes:**

fix: URL issues on any heading click/scroll

---

components/TableContents.tsx
components/post-body.tsx

- This PR fixes the hiding of the blog text on mobile devices on opening the dropdown of `table of contents`. No change on desktop TOC component.
- Changes in `components/TableContents.tsx` for revamping the TOC ui.
-
-
-
https://github.com/user-attachments/assets/1dcad5f3-d40d-4d1e-9537-caedbefdbf52
- **New Dependencies:** 
- **Configuration Changes:**

Fix: Table of contents UI hides text on mobile devices
